### ISSUE TITLE
Can't skip results of non existing package names to keep running process

### ISSUE THREAD

**Issue by alexdelbosque** [chadrem/market_bot#44]
I have some lists of package names obtained by phones and would like to run the search, but every time that a package name is not found, the script gives an error.

I am building an array with the results and would like to keep running the script and simply fill the values for package names not found with nil.

keep getting this errors
"/Users/GARCIADELBOSQUE/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/market_bot-0.14.0/lib/market_bot/android/app.rb:191:in `handle_response': Got unexpected response code: 404 (MarketBot::ResponseError)
	from /Users/GARCIADELBOSQUE/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/market_bot-0.14.0/lib/market_bot/android/app.rb:156:in `update'"

Tried changing the line 191 of app.rb to nil but keep getting the errors...

help is appreciated. 

background: I have a list of around 1k package names obtained from smartphones but many of them are system apps, so if not found on the play store, the script should keep running and fill data for the other ones...

**Comment by chadrem** [comment]
@alexdelbosque if you are still having this problem then paste a simple example that reproduces the issue so that I can try it.  Also make sure you are using the latest version of the gem.

**Comment by chadrem** [comment]
Closing this issue due to inactivity.  Feel free to re-open it if needed.  Make sure to include some code that reproduces the issue.
